opiproject/sztp

- .github/workflows/linters.yml
- Dockerfile.agent
- Dockerfile.bootstrap
- Dockerfile.client
- Dockerfile.dhcp
> ci: fix docker linter

- docker-compose.yml
- sztp-agent/Dockerfile
> add new agent to compose

- README.md
> README: howto test everything

- README.md
- docker-compose.yml
- sztp: start daemon not status
- readme: add how to test everything
> sztp: start daemon not status

- tests.sh
> ci: add compose ps for debug

- .github/workflows/linters.yml
- docker-compose.yml
> ci: add YAMLlint

- sztp-agent/Dockerfile
> Add keys and certificates to our go agent

- sztp-simulator/Dockerfile
- tests.sh
> use agent container instead of bootsrap container

- docker-compose.yml
> docker: use full path

- .github/workflows/linters.yml
- sztp-simulator/Dockerfile
- tests.sh
```
$ docker images | grep "3.10.8-slim\|7.85.0"
python           3.10.8-slim  b05ccb7cc132   16 hours ago   126MB
curlimages/curl  7.85.0       dddbb581f872    6 weeks ago   15.2MB
```
> curl: reduce docker size

- sztp-agent/pkg/secureAgent/agent.go
- sztp-agent/pkg/secureAgent/daemon.go
> parse onboarding-information json

- sztp-agent/pkg/secureAgent/agent.go
- sztp-agent/pkg/secureAgent/daemon.go
> add redirect-information struct

- sztp-agent/Dockerfile
> ci: add go testing

- sztp-simulator/.dockerignore
- sztp-simulator/Dockerfile
- sztp-simulator/progress.json
- tests.sh
> add progress

- sztp-agent/pkg/secureAgent/agent.go
- sztp-agent/pkg/secureAgent/daemon.go
- sztp-agent/pkg/secureAgent/utils.go
- sztp-agent/pkg/secureAgent/utils_test.go
> go: report progress

- sztp-agent/pkg/secureAgent/agent.go
- sztp-agent/pkg/secureAgent/daemon.go
> add ProgressType enum

- sztp-agent/main.go
- sztp-agent/pkg/secureAgent/agent.go
- sztp-agent/pkg/secureAgent/agent_test.go
- sztp-agent/pkg/secureAgent/daemon.go
- sztp-agent/pkg/secureAgent/daemon_test.go
- tests.sh
> Download image from Server

- tests.sh
> ci: remove sleep

- sztp-agent/pkg/secureAgent/daemon.go
- launch pre-configuration script
- launch post-configuration script
- Skeleton to add new scripts splitted in functions
> Pre and post configuration scripts

- docker-compose.yml
- sztp-agent/pkg/secureAgent/daemon.go
> CI: remove sleep, use healthcheck instead

- sztp-agent/cmd/daemon.go
- sztp-agent/cmd/disable.go
- sztp-agent/cmd/enable.go
- sztp-agent/cmd/run.go
- sztp-agent/cmd/status.go
- sztp-agent/pkg/secureagent/agent.go
- sztp-agent/pkg/secureagent/agent_test.go
- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/daemon_test.go
- sztp-agent/pkg/secureagent/disable.go
- sztp-agent/pkg/secureagent/enable.go
- sztp-agent/pkg/secureagent/run.go
- sztp-agent/pkg/secureagent/status.go
- sztp-agent/pkg/secureagent/utils.go
- sztp-agent/pkg/secureagent/utils_test.go
> fix issues with golint. Tested locally with golint tool

- sztp-agent/pkg/secureagent/agent.go
- sztp-agent/pkg/secureagent/agent_test.go
- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/daemon_test.go
- sztp-agent/pkg/secureagent/disable.go
- sztp-agent/pkg/secureagent/enable.go
- sztp-agent/pkg/secureagent/run.go
- sztp-agent/pkg/secureagent/status.go
> rename package and nolint some issues

- sztp-agent/pkg/secureagent/utils.go
> json: strict decoder with DisallowUnknownFields

- .github/workflows/linters.yml
> ci: add golangci to linters

- sztp-agent/pkg/secureagent/daemon_test.go
- sztp-agent/pkg/secureagent/disable.go
- sztp-agent/pkg/secureagent/enable.go
- sztp-agent/pkg/secureagent/run.go
- sztp-agent/pkg/secureagent/status.go
- sztp-agent/pkg/secureagent/utils.go
> removing functions unused from CLI status, disable and enable

- sztp-agent/pkg/secureagent/agent.go
- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/daemon_test.go
- test: add redirect convey info
- review comments
- redirect: add json parsing on BootstrapServerRedirectInfo
> test: add redirect convey info

- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/daemon_test.go
> add ProgressType argument

- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/utils.go
- sztp-agent/pkg/secureagent/utils_test.go
> report progress returns empty response

- tests.sh
> check bootstrapping log

- docker-compose.yml
> small docker compose fixes

- sztp-server/docker-entrypoint.sh
> docker: reduce code duplication

- .github/workflows/sztp.yml
- docker-compose.yml
- web/Dockerfile
avoid bind-mount the file during runtime
> add web folder

- docker-compose.yml
> Add mdns via avahi docker

- README.md
- tests.sh
> mDNS: update readme and tests

- .github/workflows/go.yml
> CI: add go

- .github/workflows/go.yml
> ci: fix coverage

- docker-compose.yml
- sztp-server/Dockerfile
- sztp-server/config/sztpd.redirect.json.template
- sztp-server/docker-entrypoint.sh
- tests.sh
> add redirecting option

- README.md
> ci: add coverage badge

- dhcp-server/dhcpd.conf.template
- sztp-agent/pkg/secureagent/daemon.go
- tests.sh
> Switch to use redirect server

- sztp-server/Dockerfile
Fix for issue #132
Signed-off-by: Louis Laborde HPE <louis.laborde@hpe.com>
> Add gcc package to Dockerfile

- sztp-agent/Dockerfile
By introducing multi-stage build, ~x10 size reduction !
Signed-off-by: Boris Glimcher <36732377+glimchb@users.noreply.github.com>
> docker: reduce images size

- docker-compose.yml
- sztp-server/docker-entrypoint.sh
> sztp: add env var SZTPD_RETRY_ATTEMPTS

- sztp-server/Dockerfile
Fix for issue https://github.com/opiproject/sztp/issues/158
Signed-off-by: Louis Laborde HPE <louis.laborde@hpe.com>
> sztpd doesn't work with sqlalchemy version 2.x

- docker-compose.yml
- sztp-server/Dockerfile
- sztp-server/config/sztpd.redirect.json.template
- sztp-server/config/sztpd.running.json.template
- sztp-server/docker-entrypoint.sh
- tests.sh
this is much mnore accurate for health check
since after service restart port is changing and service is healthy
only after restart with configuration
> sztpd: separate SZTPD_INIT_PORT vs SZTPD_NBI_PORT

- .github/workflows/sztp.yml
- dhcp-server/Dockerfile
- dhcp-server/dhcpd.conf.template
- docker-compose.yml
- tests.sh
> Replace opi-dhcp-server with networkboot/dhcpd

- .github/workflows/sztp.yml
- README.md
- docker-compose.yml
- sztp-server/config/sztpd.running.json.template
- tests.sh
- web/Dockerfile
> Replace opi-web-server with httpd-alpine

- .github/workflows/sztp.yml
- dhcp-client/Dockerfile
- docker-compose.yml
> replace opi-dhcp-client with modularitycontainers

- README.md
- docker-compose.yml
- tests.sh
> rename agent to simulator

- .github/workflows/sztp.yml
> Publish sztp to dockerhub as well

- README.md
> docs: docker compose vs docker-compose

- sztp-agent/cmd/daemon.go
- sztp-agent/cmd/disable.go
- sztp-agent/cmd/enable.go
- sztp-agent/cmd/run.go
- sztp-agent/cmd/status.go
- sztp-agent/pkg/secureagent/agent.go
- sztp-agent/pkg/secureagent/agent_test.go
- sztp-agent/pkg/secureagent/disable_test.go
- sztp-agent/pkg/secureagent/enable_test.go
- sztp-agent/pkg/secureagent/run_test.go
- sztp-agent/pkg/secureagent/status_test.go
- sztp-agent/pkg/secureagent/utils.go
> feat: expose dhclient.leases as argument

- docker-compose.yml
> ci: expose relevant ports

- sztp-agent/pkg/secureagent/utils.go
from ci:
```
=== RUN   TestAgent_doReqBootstrap/Test_KO_getting_error_with_basic_auth
2024/06/05 01:39:09 [INFO] Starting the Request to get On-boarding Information.
2024/06/05 01:39:09 KO KO
Error: 39:09 [ERROR]  [ERROR] Expected conveyed-information, received error type=protocol, tag=access-denied, message=failed
```
> fix: handle ietf-restconf:errors

- sztp-agent/pkg/secureagent/daemon_test.go
> fix: linter switch case

- sztp-agent/pkg/secureagent/daemon.go
> fix: report more progress in new places

- sztp-agent/pkg/secureagent/agent.go
- sztp-agent/pkg/secureagent/agent_test.go
- sztp-agent/pkg/secureagent/daemon.go
> fix(progress): add ssh-host-keys to reporting progress

- sztp-agent/pkg/secureagent/agent_test.go
- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/daemon_test.go
> fix(sztp): send ssh key when onboarding completed

- sztp-agent/cmd/daemon_test.go
- sztp-agent/cmd/disable.go
- sztp-agent/cmd/disable_test.go
- sztp-agent/cmd/enable.go
- sztp-agent/cmd/enable_test.go
- sztp-agent/cmd/run.go
- sztp-agent/cmd/run_test.go
- sztp-agent/cmd/status.go
- sztp-agent/cmd/status_test.go
- sztp-agent/main.go
- sztp-agent/pkg/secureagent/agent.go
- sztp-agent/pkg/secureagent/agent_test.go
- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/daemon_test.go
- sztp-agent/pkg/secureagent/disable.go
- sztp-agent/pkg/secureagent/disable_test.go
- sztp-agent/pkg/secureagent/enable.go
- sztp-agent/pkg/secureagent/enable_test.go
- sztp-agent/pkg/secureagent/run.go
- sztp-agent/pkg/secureagent/run_test.go
- sztp-agent/pkg/secureagent/status.go
- sztp-agent/pkg/secureagent/status_test.go
- sztp-agent/pkg/secureagent/utils.go
- sztp-agent/pkg/secureagent/utils_test.go
> fix: linter

- README.md
- docker-compose.yml
- scripts/change_image.sh
- scripts/tests.sh
- sztp-agent/pkg/secureagent/daemon.go
- sztp-server/config/sztpd.running.json.template
> fix(web): switch to https

- docker-compose.yml
> fix(web): enable SSLVerifyClient on web server

- docker-compose.yml
> fix(web): copy client in addition to server certs

- scripts/tests.sh
- sztp-agent/Dockerfile
- sztp-agent/cmd/daemon.go
> fix(agent): move certs to a folder, avoid root

- .github/workflows/sztp.yml
- docker-compose.yml
- sztp-agent/Dockerfile
> fix(certs): remove certs from client docker image

- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/utils.go
> fix: refactor simplify struct init code

- sztp-agent/pkg/secureagent/daemon.go
> fix: deprecate use of ioutil package

- sztp-agent/cmd/daemon.go
- sztp-agent/cmd/daemon_test.go
- sztp-agent/cmd/disable.go
- sztp-agent/cmd/disable_test.go
- sztp-agent/cmd/enable.go
- sztp-agent/cmd/enable_test.go
- sztp-agent/cmd/run.go
- sztp-agent/cmd/run_test.go
- sztp-agent/cmd/status.go
- sztp-agent/cmd/status_test.go
> fix: linter issue

- scripts/tests.sh
- sztp-agent/Dockerfile
- sztp-agent/input.json
- sztp-agent/progress.json
> fix: remove json files

- docker-compose.yml
- sztp-server/Dockerfile
- sztp-server/docker-entrypoint.sh
> fix: move image binary from dockerfile to runtime

- docker-compose.yml
- sztp-server/docker-entrypoint.sh
> fix(certs): use mounted certs instead of built into image ones

- scripts/keys.sh
> fix: helper script change container name

- docker-compose.yml
- sztp-server/Dockerfile
> fix: remove certs from sztp image completely

- docker-compose.yml
- sztp-server/Dockerfile
- sztp-server/docker-entrypoint.sh
> fix(server): move config files from buildtime to runtime

- .github/workflows/sztp.yml
- docker-compose.yml
- sztp-server/Dockerfile
> fix(server): remove docker image completely

- README.md
- docker-compose.yml
- scripts/logs.sh
- scripts/tests.sh
- sztp-server/config/sztpd.redirect.json.template
- sztp-server/config/sztpd.running.json.template
> fix(agent): rename my-serial-number for testing

- README.md
- docker-compose.yml
- scripts/logs.sh
- scripts/tests.sh
- sztp-server/config/sztpd.redirect.json.template
- sztp-server/config/sztpd.running.json.template
> fix: rename opi-serial-number to third-serial-number

- docker-compose.yml
> fix(certs): avoid curl install

- scripts/tests.sh
> test: code duplication

- scripts/tests.sh
> test: small refactor

- scripts/tests.sh
> test: add --fail to curl

- docker-compose.yml
- scripts/run_agent.sh
> fix: explicit cmdline parameters

- scripts/tests.sh
> test: small var rename

- scripts/tests.sh
> fix: switch agent to curl images

- docker-compose.yml
- scripts/tests.sh
> feat(ci): spin 3 agents

- README.md
- scripts/keys.sh
> docs: fix readme to match code

- sztp-agent/cmd/daemon.go
- sztp-agent/pkg/secureagent/agent.go
- sztp-agent/pkg/secureagent/utils.go
> feat(agent): disover serial number if not given

- docker-compose.yml
- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/utils.go
> fix(certs): avoid irrelevant compilation

- scripts/tests.sh
> test: code dup removal

- scripts/tests.sh
> test: small add for explicit get request

- sztp-agent/cmd/daemon.go
> fix: add user input validation

- .golangci.yml
- sztp-agent/cmd/daemon.go
- sztp-agent/cmd/daemon_test.go
- sztp-agent/cmd/disable.go
- sztp-agent/cmd/disable_test.go
- sztp-agent/cmd/enable.go
- sztp-agent/cmd/enable_test.go
- sztp-agent/cmd/run.go
- sztp-agent/cmd/run_test.go
- sztp-agent/cmd/status.go
- sztp-agent/cmd/status_test.go
- sztp-agent/main.go
- sztp-agent/pkg/secureagent/agent.go
- sztp-agent/pkg/secureagent/agent_test.go
- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/daemon_test.go
- sztp-agent/pkg/secureagent/disable.go
- sztp-agent/pkg/secureagent/utils.go
Closes https://github.com/opiproject/sztp/issues/390
> fix: golangci-lint errors and warnings

- docker-compose.yml
- scripts/run_agent.sh
- sztp-agent/pkg/secureagent/daemon.go
- sztp-agent/pkg/secureagent/daemon_test.go
- sztp-agent/pkg/secureagent/utils.go
- sztp-agent/pkg/secureagent/utils_test.go
> fix: fill read ssh host key pub keys

- scripts/run_agent.sh
- sztp-agent/pkg/secureagent/utils.go
> ci: add readonly bind mount option

- sztp-agent/pkg/secureagent/agent_test.go
> test: getserialnumber via smbios

- .github/PULL_REQUEST_TEMPLATE.md
> chore: add PR Template

- docker-compose.yml
- scripts/tests.sh
Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue
- Please add the links to the dependent PR need to be merged before this (if any).
> tests: add tpm test

- docker-compose.yml
- scripts/tests.sh
Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue
- Please add the links to the dependent PR need to be merged before this (if any).
> ci: avoid apt install

- sztp-agent/pkg/dhcp/dbus.go
- sztp-agent/pkg/dhcp/dbus_tests.go
- sztp-agent/pkg/dhcp/leases.go
- sztp-agent/pkg/dhcp/leases_tests.go
- sztp-agent/pkg/dhcp/utils.go
- sztp-agent/pkg/dhcp/utils_tests.go
Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue
- Please add the links to the dependent PR need to be merged before this (if any).
> ci: prepare folder structure for dhcp feature

- sztp-agent/pkg/secureagent/ssh_test.go
Add tests to cover all code paths for ssh
> refactor: add more test for ssh.go
