.github/workflows/sztp.yml, Dockerfile.bootstrap
=> ci: fix echo errors that fail ci

sztp-agent/cmd/daemon.go, sztp-agent/cmd/disable.go, sztp-agent/cmd/enable.go, sztp-agent/cmd/run.go, sztp-agent/cmd/status.go, sztp-agent/go.mod, sztp-agent/go.sum, sztp-agent/main.go, sztp-agent/pkg/secureAgent/agent.go, sztp-agent/pkg/secureAgent/daemon.go, sztp-agent/pkg/secureAgent/disable.go, sztp-agent/pkg/secureAgent/enable.go, sztp-agent/pkg/secureAgent/run.go, sztp-agent/pkg/secureAgent/status.go
First part of the skeleton with the basic structure to generate a cli and daemon for the new sztp-agent
=> first skeleton structure for szpt-agent

.github/workflows/linters.yml, sztp-agent/Dockerfile, sztp-agent/go.mod
=> add dockerfile

sztp-agent/pkg/secureAgent/daemon.go
- refactor pre and post configuration 
- create copy configuration file to device
Tested locally and [CI](https://github.com/opiproject/sztp/actions/runs/3295659691) passed:
=> copy configuration and refactor pre and post function

sztp-agent/pkg/secureAgent/daemon.go, sztp-agent/pkg/secureAgent/daemon_test.go, sztp-agent/pkg/secureAgent/utils_test.go
Also allow testing like this:
```
docker run --rm -it -e CGO_ENABLED=0 -v `pwd`:/app -w /app golang:alpine go test -v /app/...
```
=> JSON: fail on errors in json

sztp-agent/cmd/daemon.go, sztp-agent/cmd/disable.go, sztp-agent/cmd/enable.go, sztp-agent/cmd/run.go, sztp-agent/cmd/status.go, sztp-agent/go.mod, sztp-agent/go.sum, sztp-agent/main.go, sztp-agent/pkg/secureAgent/agent.go, sztp-agent/pkg/secureAgent/agent_test.go, sztp-agent/pkg/secureAgent/daemon.go, sztp-agent/pkg/secureAgent/daemon_test.go, sztp-agent/pkg/secureAgent/disable.go, sztp-agent/pkg/secureAgent/enable.go, sztp-agent/pkg/secureAgent/run.go, sztp-agent/pkg/secureAgent/status.go, sztp-agent/pkg/secureAgent/utils.go
=> fix issues with golint. Tested locally with golint tool

docker-compose.yml
=> mDNS: add client via nmap

sztp-server/Dockerfile
=> Add DNS to certificates

sztp-agent/cmd/daemon_test.go, sztp-agent/cmd/disable_test.go, sztp-agent/cmd/enable_test.go, sztp-agent/cmd/run_test.go, sztp-agent/cmd/status_test.go, sztp-agent/go.sum, sztp-agent/pkg/secureagent/agent_test.go, sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/daemon_test.go, sztp-agent/pkg/secureagent/disable_test.go, sztp-agent/pkg/secureagent/enable_test.go, sztp-agent/pkg/secureagent/run_test.go, sztp-agent/pkg/secureagent/status_test.go
Adding more tests to daemon and other files: 
83.2% coverage reached
=> Adding more tests to daemon and the rest of files

.github/workflows/sztp.yml
Since client refence the server image during build:
```
COPY --from=ghcr.io/opiproject/opi-sztp-server:main
```
we need to build server first to make publish work correctly.
the problem was not showing during normal compose builds
=> ci: build clients AFTER servers

docker-compose.yml, scripts/logs.sh, scripts/tests.sh
- fix: 7080 was used for both redirecter and bootstrap
- feat: add script to fetch bootstrap logs
=> feat: add script to fetch bootstrap logs

.github/workflows/go.yml
golangci is failing on main, and it requires a separate PR to fix all cases
=> chore: Go update

sztp-agent/pkg/secureagent/agent.go, sztp-agent/pkg/secureagent/daemon_test.go
from ci:
```
#18 12.45 === RUN   TestAgent_doReqBootstrap/Test_KO_getting_error_with_basic_auth
#18 12.45 2024/06/05 01:21:17 [INFO] Starting the Request to get On-boarding Information.
#18 12.45 2024/06/05 01:21:17 KO KO
#18 12.45 2024/06/05 01:21:17 [ERROR]  json: unknown field "ietf-restconf:errors"
```
=> test: add 401 wrong auth test

sztp-agent/cmd/daemon_test.go, sztp-agent/cmd/disable_test.go, sztp-agent/cmd/enable_test.go, sztp-agent/cmd/run_test.go, sztp-agent/cmd/status_test.go, sztp-agent/main.go, sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/utils.go
/app # go install golang.org/x/tools/cmd/goimports@latest
/app # goimports -w /app
=> refactor: fix go imports after rename

README.md, sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/daemon_test.go
=> fix(progress): remove redundant function argument

docker-compose.yml
instead of generating new ones
=> fix(cert): reuse bootstrap certs for web

scripts/tests.sh, sztp-agent/pkg/secureagent/agent.go, sztp-agent/pkg/secureagent/agent_test.go, sztp-agent/pkg/secureagent/daemon.go
=> fix: add trust-anchor-cert to progress

sztp-server/Dockerfile, sztp-server/docker-entrypoint.sh
This allows to change certs in runtime
=> fix: move certs from build to runtime

sztp-server/config/sztpd.running.json.template, sztp-server/docker-entrypoint.sh
=> feat: prepare for more then single device

docker-compose.yml, scripts/run_agent.sh, sztp-agent/cmd/daemon.go, sztp-agent/pkg/secureagent/daemon.go
=> fix: allow to skip dhcp using url option

sztp-agent/pkg/secureagent/tls.go, sztp-agent/pkg/secureagent/tls_test.go, sztp-agent/pkg/secureagent/utils.go, sztp-agent/pkg/secureagent/utils_test.go
=> refactor: move tls to a separate file

docker-compose.yml, sztp-agent/cmd/run.go, sztp-agent/main.go, sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/run.go, sztp-agent/pkg/secureagent/run_test.go
closes https://github.com/opiproject/sztp/issues/396
=> fix: loop bootstrap sequence in daemon, add run command and agent

sztp-agent/cmd/cli.go, sztp-agent/cmd/daemon.go, sztp-agent/cmd/daemon_test.go, sztp-agent/cmd/disable.go, sztp-agent/cmd/disable_test.go, sztp-agent/cmd/enable.go, sztp-agent/cmd/enable_test.go, sztp-agent/cmd/run.go, sztp-agent/cmd/run_test.go, sztp-agent/cmd/status.go, sztp-agent/cmd/status_test.go, sztp-agent/main.go
This PR fixes #413 
I know that using `init()` funcs are not the ideal approach in most cases and is often disregarded and recommended against in Go. But, for the Cobra CLI and the structure of the current source I thought it be necessary for specific reasons. Cobra also recommend this way.
However, I did this a little different to try to avoid the problems with `init()` as much as possible.
Comparatively to the original issue #413:
1. Global slice of `*cobra.command` for the `cmd` pkg 
2. Each command file has an `init()` function that appends the command to the global slice, this is separate from the command functions themselves
This way, we kept the original structure of the command functions so that `init()` doesn't interfere with the testing of the commands. And, if need be, the …
=> Closes #413

sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/daemon_test.go
this better reflects what function is doing.
and it separates from public `GetBootstrapURL` func
`discoverBootstrapURLs` retrieves URLs from dhcp lease file
In the next patches it will also fetch them from network manager
Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue
- Please add the links to the dependent PR need to be merged before …
=> refactor: rename getBootstrapURL to discoverBootstrapURLs

sztp-agent/pkg/secureagent/agent.go, sztp-agent/pkg/secureagent/agent_test.go, sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/daemon_test.go
- if user gave us URL, use it
- else if user gave us lease file, use it
- else try to fecth from network manager via dbus
=> refactor: put logic in discoverBootstrapURLs

.github/workflows/binaries.yaml, .github/workflows/release.yaml, .gitignore, .goreleaser.yaml
This PR introduces the option to build 64bit binaries for x86_64 and arm64.The releases are generated when new tags are created and pushed to the repo.
I was able to simulate it on my fork https://github.com/h0lyalg0rithm/sztp/actions/runs/10165872886
I have set the go version to 1.19 instead of 1.20 or 1.21 because of the go.mod version
Refers to this issue #432 
=> ci: Build binaries using goreleaser

.github/workflows/linters.yml
Upgrade linter action for better issue visibility.
The offending line shows up in the action run.
Sample output
https://github.com/h0lyalg0rithm/sztp/actions/runs/10222129019/job/28286107496
=> ci: Update linter action to v6

sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/utils.go, sztp-agent/pkg/secureagent/utils_test.go
Move sha256 calculation to utils.go file.
Add tests to validate change
=> refactor: move checksum calculation to utils

sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/daemon_test.go
Adds tests for bootstrap redirect logic
=> refactor: add tests for bootstrap redirect

docker-compose.dpu.yml, docker-compose.yml
Based on the previous change https://github.com/opiproject/sztp/pull/315
Split the docker compose file into dpu and server file
=> refactor: split docker compose into server | dpu files

docker-compose.dpu.yml, scripts/run_agent.sh, sztp-agent/cmd/daemon.go, sztp-agent/cmd/disable.go, sztp-agent/cmd/enable.go, sztp-agent/cmd/run.go, sztp-agent/cmd/status.go, sztp-agent/pkg/secureagent/agent.go, sztp-agent/pkg/secureagent/agent_test.go, sztp-agent/pkg/secureagent/configuration.go, sztp-agent/pkg/secureagent/daemon.go, sztp-agent/pkg/secureagent/image.go, sztp-agent/pkg/secureagent/progress_test.go, sztp-agent/pkg/secureagent/run.go, sztp-agent/pkg/secureagent/status.go, sztp-agent/pkg/secureagent/status_test.go, sztp-agent/pkg/secureagent/utils.go, sztp-agent/pkg/secureagent/utils_test.go
=> feat: status command
